# Generated by Django 5.1.2 on 2024-11-23 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=8)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_credito', models.CharField(choices=[('VIGENTE', 'Vigente'), ('TERMINADO', 'Terminado'), ('INCUMPLIDO', 'Incumplido')], max_length=50)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos', to='prestamos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('ocupacion', models.CharField(max_length=150)),
                ('fecha_inicio_ocupacion', models.DateField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_ocupacion', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='prestamos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad_pagos', models.IntegerField()),
                ('inicio_pago', models.DateField()),
                ('fin_pago', models.DateField()),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pagos', to='prestamos.credito')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADO', 'Realizado'), ('ATRASADO', 'Atrasado'), ('INCUMPLIDO', 'Incumplido')], default='PENDIENTE', max_length=50)),
                ('dias_atraso', models.IntegerField(default=0)),
                ('plan_pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='prestamos.planpagos')),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas', to='prestamos.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='credito',
            name='prenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos', to='prestamos.prenda'),
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_solicitud', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE', 'Pendiente')], max_length=50)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='prestamos.cliente')),
                ('prenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='prestamos.prenda')),
            ],
        ),
        migrations.AddField(
            model_name='credito',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='prestamos.solicitudcredito'),
        ),
    ]
