# Generated by Django 5.1.2 on 2024-11-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detallecliente',
            name='total_ingresos',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
